services:
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - app-network


  python-app:
      image: python:3.9-slim
      container_name: slim-python
      depends_on:
        - redis
      volumes:
        - ./scripts:/app
      working_dir: /app
      networks:
        - app-network
      command: bash -c "pip install redis && tail -f /dev/null"


networks:
  app-network:
    driver: bridge